### ISSUE TITLE
Пакет для передачи данных из фронтенда в бэкенд

### ISSUE THREAD

**Issue by DmitryNeposidjaka** [alexeymezenin/laravel-best-practices#1]
**Подскажите, пожалуйста такие пакеты для передачи данных.
Возможно узнать вашу почту или контакты, для вопросов?**
_можете ответить на почту_ dmitryneposidjaka@gmail.com

![_075](https://user-images.githubusercontent.com/13102394/32371644-5055a50c-c09a-11e7-9d2b-a096a04e4e6a.png)

**Comment by alexeymezenin** [comment]
[Вот самый популярный](https://github.com/laracasts/PHP-Vars-To-Js-Transformer). Хороший пакет, но мне он не нравится загрязнением глобальными переменными. Я использую свой код, который планирую оформить в пакет с самом ближайшем будущем.

**Comment by itelmenko** [comment]
Привет всем!

Кто подскажет чем именно плох подход

```
let article = `{{ json_encode($article) }}`;
```

Почему передавать js структуры в hidden полях предпочтительнее?

И вот рекомендуемый пакет в своем readme тоже не имеет объяснения в чем состоит боль
> Traditionally, this can be a bit of a pain - especially as your app grows.
