### ISSUE TITLE
Добавьте пункт к соглашению об именовании

### ISSUE THREAD

**Issue by PetrKravets** [alexeymezenin/laravel-best-practices#10]
Добавьте, пожалуйста, пункт к "Соглашение сообщества об именовании", как правильно именовать переменные в представлении? CamelCase или underscore?
$user->full_name vs. $user->fullName ?

**Comment by leep0o** [comment]
CamelCase  $user->fullName

**Comment by PetrKravets** [comment]
Ну сам автор в своих примерах использует underscore
// View
{{ $object->ordered_at->toDateString() }}
{{ $object->ordered_at->monthDay }}

https://github.com/alexeymezenin/laravel-best-practices#store-dates-in-the-standard-format-use-accessors-and-mutators-to-modify-date-format

**Comment by alexeymezenin** [comment]
Добавил пункт "свойство модели". Также исправил ошибку с `->monthDay`. Спасибо, что обратили внимание на это.
