### ISSUE TITLE
Is there a way to print this?

### ISSUE THREAD

**Issue by FoxRocks76** [alexeymezenin/laravel-best-practices#109]
First, thank you to those who have made this possible, as a new developer I find this extremely helpful!

I was wondering if there's a way to print this out so I can have it available offline for when I'm not at my desk.

**Comment by nullifiedaccount** [comment]
This is all in markdown, why not use copy it and render it to your taste and print?

**Comment by spekulatius** [comment]
As of now it's not interested to be printed. A bookmark gets you the latest and greatest on every click ;)
