### ISSUE TITLE
Do not get data from the .env file directly, why?

### ISSUE THREAD

**Issue by PengYilong** [alexeymezenin/laravel-best-practices#118]
I am using the bad way.
```php
$apiKey = env('API_KEY');
```

**Comment by alexeymezenin** [comment]
@PengYilong it's a good idea to do that to avoid obscurity when working in teams. Another reason is [configuration caching](https://laravel.com/docs/8.x/configuration#configuration-caching):

> If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded; therefore, the env function will only return external, system level environment variables.

**Comment by PengYilong** [comment]
thanks @alexeymezenin
