### ISSUE TITLE
Wrong return type?

### ISSUE THREAD

**Issue by mpspm** [alexeymezenin/laravel-best-practices#124]
Under the single responsibility principle "good" example, should the return type for getFullNameAttribute() be "string" and not "bool"?

```
public function getFullNameAttribute(): bool
{
    return $this->isVerifiedClient() ? $this->getFullNameLong() : $this->getFullNameShort();
}
```

**Comment by Sterioss** [comment]
I suspect this is a mistake since calling this function would cause an error. The two ternary options both return string type values.
