### ISSUE TITLE
PSR-12

### ISSUE THREAD

**Issue by gkakosouris** [alexeymezenin/laravel-best-practices#126]
Should we update the linked PSR standard to [PSR-12](https://www.php-fig.org/psr/psr-12/)?

**Comment by Dibbyo456** [comment]
We should.

**Comment by NicoHood** [comment]
I've noticed this as well when looking at the readme. Are there any essential changes, that you already know?

**Comment by spekulatius** [comment]
Thanks for pointing it out. I've updated this :muscle:
