### ISSUE TITLE
Views and assets dirnames with two words

### ISSUE THREAD

**Issue by z-h-z-h** [alexeymezenin/laravel-best-practices#13]
How to name?

**Views**
1. /resources/views/TwoWords/view.blade.php
2. /resources/views/twoWords/view.blade.php
3. /resources/views/twowords/view.blade.php
4. /resources/views/two_words/view.blade.php

**Assets**

1. /resources/assets/js/components/TwoWords/MyComponent.vue
2. /resources/assets/js/components/twoWords/myComponent.vue
3. /resources/assets/js/components/twowords/mycomponent.vue
4. /resources/assets/js/components/two_words/my_component.vue

**Comment by skyrpex** [comment]
My two cents:

**Views:** I don't use Laravel views anymore, but I find using camelCase the best option (for consistency with PHP namespace directories and classes).

- resources/views/projectDetails/header.blade.php

**Assets:** I also use camelCase for JS files, except for files that export classes or Vue components.

- resources/assets/js/renderContext.js
- resources/assets/js/App.js
- resources/assets/js/components/Nav.vue

**Comment by alexeymezenin** [comment]
@z-h-z-h I think these are fine

>/resources/views/two_words/view.blade.php
>/resources/views/twoWords/view.blade.php

>/resources/assets/js/components/TwoWords/MyComponent.vue

Because of the [Vue 2 style guide](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential)
