### ISSUE TITLE
Converting from and back to json

### ISSUE THREAD

**Issue by NicoHood** [alexeymezenin/laravel-best-practices#136]
Hi!
I found some very useful stuff in here, that makes it easier for me as a beginner to get things right. What I did not understand yet is how to properly convert a model from and to json. I've posted my question on stackoverflow, so more people can find it. If someone has a good tip on that, we could add it to this repository as well.

https://stackoverflow.com/questions/72377838/convert-json-request-to-eloquent-model-and-back-to-database

Thanks :)

**Comment by spekulatius** [comment]
Hey @NicoHood 

Thanks for this, closing it for now. Feel free to come back to it once the question has been clarified fully.

Cheers
