### ISSUE TITLE
pivotTables

### ISSUE THREAD

**Issue by shez1983** [alexeymezenin/laravel-best-practices#14]
the only issue i have is with pivot_tables.. most times you want to name them so when you look at your tables in database you know what they are.. user_article may not tell you but something like users_favourited_article  etc will

**Comment by Kyslik** [comment]
@shez1983 `user_article` is used so Laravel can guess your tables and you do not have to specify them in the relation definition

>The  `role_user` table is derived from the alphabetical order of the related model names, and contains the `user_id` and `role_id` columns.

Source https://laravel.com/docs/5.6/eloquent-relationships#many-to-many

**Comment by BenSampo** [comment]
If you want to me more descriptive about your pivot table, you can set a model to describe the intermediate table.

See the section titled "Defining Custom Intermediate Table Models" in the docs:

https://laravel.com/docs/5.6/eloquent-relationships#many-to-many

**Comment by alexeymezenin** [comment]
Using a custom more descriptive pivot table name is not bad but I would use the standard `article_user` table name if two models have just one many-to-many relation.
