### ISSUE TITLE
Typo Issue in example (Don't repeat yourself (DRY))

### ISSUE THREAD

**Issue by Mrabdlrhman** [alexeymezenin/laravel-best-practices#140]
In the "Good section" we call the "Active" function which exists in the "Bad section". So correct we need to call the "scopeActive" function

![image](https://user-images.githubusercontent.com/27730825/180638272-c1d2fd86-f041-40e9-8bfe-d0db040c6508.png)

**Comment by Konafets** [comment]
Hey, 

the code example in "good" section do not call the `active()` function from the "bad" section. 

1. there is no `active()` function in the bad section. Its called `getActive()` and its not called anywhere.
2. the good section defines a scope -> `activeScope()´ which gets called via `->active()`. You do not call `scopeActive()` as Laravel is smart enough to call that. 

Please read the documentation to understand the idea of scopes: https://laravel.com/docs/9.x/eloquent#local-scopes

**Comment by Mrabdlrhman** [comment]
Hi Konafets,

Thanks for sharing the link.
