### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by xotrs** [alexeymezenin/laravel-best-practices#15]
Hi, alexeymezenin!

I'm writing here because I don't know how to contact you.

First, thank you for a good article laravel best practices.

I want to spread this good article in Korea.

So I want to translate Korean. If you allow I'll fork your branch and then translate it.

Thanks :D

**Comment by alexeymezenin** [comment]
Please give me your email

**Comment by xotrs** [comment]
Thanks, xotrs1@gmail.com

**Comment by aozen** [comment]
Hey Alexey, i can translate Turkish in a few weeks. If you want, please contact me.
aliozendev@gmail.com
