### ISSUE TITLE
Seeder in singular -> Good, Seeder in plural -> bad (naming-conventions)

### ISSUE THREAD

**Issue by FranciscoCaldeira** [alexeymezenin/laravel-best-practices#151]
On the **follow-laravel-naming-conventions**  there is nothing about seeding. Laravel names in singular as the example from docs show.
[docs](https://laravel.com/docs/8.x/seeding#calling-additional-seeders)

I can fork this!

**Comment by spekulatius** [comment]
Hey @FranciscoCaldeira 

good point, could you add it in the readmes?

Cheers,
Peter

**Comment by FranciscoCaldeira** [comment]
It is done one [here](https://github.com/alexeymezenin/laravel-best-practices/pull/152).
