### ISSUE TITLE
Change test case methods to snake_case

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [alexeymezenin/laravel-best-practices#158]
The official Laravel documentation and all Laracast videos all follow the convention that methods in test classes use snake_case. Suggest that Laravel Best Practices follows this guideline rather than deviate from it. See: #157

**Comment by spekulatius** [comment]
Merged, thank you @JohnnyWalkerDigital

**Comment by JohnnyWalkerDigital** [comment]
Apparently there was a discussion on the issue of Laravel's support for snake_case in test case methods here previously. Is it worth having that discussion again because (IMO) it's clearly become the standard.
