### ISSUE TITLE
Error on Use accessors and mutators to modify date format

### ISSUE THREAD

**Issue by yannakos** [alexeymezenin/laravel-best-practices#17]
Laravel 5.7

I followed the steps, when i use
`{{ $user->dob->some_date }}`

getting error `Unknown getter 'some_date'`

**Comment by alexeymezenin** [comment]
Hi. You should [create an accessor](https://laravel.com/docs/5.7/eloquent-mutators#defining-an-accessor).

Or add it to the [`$dates` array](https://laravel.com/docs/5.7/eloquent-mutators#date-mutators).
