### ISSUE TITLE
What are your thought on this?

### ISSUE THREAD

**Issue by appkr** [alexeymezenin/laravel-best-practices#21]
#### Business logic should be in service class
- I don't think it's best practice to pass a Laravel's Request object to the Service Layer.
- Why? 
    - Because, it's HTTP specific data object. If your Service Object depends on delivery mechanism, you can't reuse the service object in Console Command or Queue Job.
    - Furthermore the Request object is an object from the framework, and HEAVY.
![laravel_request](https://user-images.githubusercontent.com/6471947/47292910-72aea080-d643-11e8-9dbf-fa764e063fb1.png)
    - I know you may argue that not only the Request object is already on the memory and passing it is merely a memory reference in the runtime, also additional unnecessary memory usage due to Dto object. But in personal I'll choose maintenability and readibility.
- Then what? 
    - I'd like you to use a Boundary Object, namely Dto. 
    - Make the Laravel Request object new up a Dto. And make the Service object use Dto.
```php
Class CreateUserRequest
{
    public function rules()
    {
        return [
            // ...
        ];
    }

    public function getUserDto()
    {
        return new UserDto(
            $this->input('user_name', null),
            // ...
        );
    }
}

Class UserController
{
    public function createUser(CreateUserRequest $request, UserCreator $creator)
    {
        $dto = $request->getUserDto();
        DB::transaction(function () use ($creator, $dto) {
            $user = $creator->createUser($dto);
            $user->save();
        });

        // ...
    }
}

Class CreateUserCommand
{
    public function handle(UserCreator $creator)
    {
        $dto = new UserDto(
            $this->argument('user_name'),
            // ...
        );
        DB::transaction(function () use ($creator, $dto) {
            $user = $creator->createUser($dto);
            $user->save();
        });

        // ...
    }
}
```

#### Don't repeat yourself (DRY)
- I don't like `whereHas()` example.
- Because under the the hood, the query builder translate `whereHas()` to `exists` subquery.
- And it leads you to a huage performance degradation, especially when you have a large volume of records.

#### Mass assignment
- I don't think mass assignment is a good practice, when your service is NOT TRIVIAL.
- As the document mentioned earlier, I would recommend to use a Sservice Object and mutate each property one by one.
- For example:
```php
class UserCreator
{
    public function createUser(UserDto $dto)
    {
        $user = new User();
        $user->name = $dto->getUserName();
        // You can hook into Model Validation(==Business Policy) logic here
        // With mass assignment, you will loose the model validation chance
        // ...
        return $user;
    }
}

class UserModifier
{
    public function modifyUser(User $user, UserDto $dto)
    {
        $name = $dto->getUserName();
        if ($name !== null) {
            // Again you can do the model validation here
            $user->name = $name;
        }
        // ...
        // Donot return the $user, because it was passed by reference.
    }
}
```

#### Use shorter and more readable syntax where possible
- Maybe it's OK to use Laravel's global helper functions in a Controller but not in a Domain Logic.
- I think the document is leading people being tightly coupled to the framework.

**Comment by appkr** [comment]
Catastrophic, Github today is. I put an example of Dto, but it's gone. So reposting it.

```php
Class CreateUserRequest
{
    public function rules()
    {
        return [
            // ...
        ];
    }

    public function getUserDto()
    {
        return new UserDto(
            $this->input('user_name', null),
            // ...
        );
    }
}

Class UserController
{
    public function createUser(CreateUserRequest $request, UserCreator $creator)
    {
        $dto = $request->getUserDto();
        DB::transaction(function () use ($creator, $dto) {
            $user = $creator->createUser($dto);
            $user->save();
        });

        // ...
    }
}

Class CreateUserCommand
{
    public function handle(UserCreator $creator)
    {
        $dto = new UserDto(
            $this->argument('user_name'),
            // ...
        );
        DB::transaction(function () use ($creator, $dto) {
            $user = $creator->createUser($dto);
            $user->save();
        });

        // ...
    }
}
```

**Comment by skyrpex** [comment]
If I'm not mistaken, what you're explaining is very similar to DDD. Here's is a [recent blog post](https://stitcher.io/blog/organise-by-domain) from Spatie people (I believe).

I have to say that I'm so happy I started working that way. Separating domain layers from the framework is so beneficial in terms of maintainability.

**Comment by skyrpex** [comment]
Of course, there's no silver bullet but this pattern worked for me for medium to large sized applications. Small applications can be coded whatever, though.

**Comment by alexeymezenin** [comment]
Hi. Thank you for the feedback.

>I don't think it's best practice to pass a Laravel's Request object to the Service Layer.

`$request->file('image')` is not a Request object.

> I don't like whereHas() example.

I always use Eloquent to keep the code maintainable. The tiny performance difference is not a problem for most of Laravel projects. Development and maintenance costs are more important.

If you have a couple of really slow queries that became a problem, you can always rewrite those into query builder queries or raw SQL queries, use cache etc.

> I don't think mass assignment is a good practice, when your service is NOT TRIVIAL.

I always use the mass assignment feature. It's absolutely safe when you know how it works.

>I think the document is leading people being tightly coupled to the framework.

Technically, that is correct but I still prefer to use the helpers because they make the code maintainable.

Overengineering is not good.

>Don’t try to apply DDD for everything. Draw a context map and decide where you will make a push for DDD and where you will not (author of DDD)

Yes, the app will be tightly coupled with a couple of classes (not with the framework) but if you'll really want to transfer Laravel code to another PHP framework, this will be your smallest problem. By the way, it's super easy (cheap) to make all these helpers work in any PHP framework or in a vanilla PHP application.

Also, in the real world, a typical small business will keep using the existing app or rewrite the app using another programming language or framework from scratch rather than try to reuse old sloppy code in some new fancy PHP framework.

**Comment by appkr** [comment]
@alexeymezenin Your answer is understandable, and totally I agree with you. I didn't mean to offend you (not a native speaker, so don't know write nicely), I just wanted to know how people think. Thanks.

**Comment by appkr** [comment]
@skyrpex I have looked through the Spatie's value object. Thanks for the link.

I do like and really respect the Spatie people and their packages though, but this time, I will not buy the concept of the Value Object(VO) from them. I think they mix up the concept of VO between Data Transfer Object(DTO).

My idea is based on Martin Fowler's book "Patterns of Enterprise Application Architecture", and definitions of VO from the Red Book by Eric Evans.

If you happen to have an interest on VO, the following is the VO example in a Laravel project based on which I understood the concept. You may say, a lot of boilerplate code. But the decision is yours. Since I work for a growing Logistics sevice which currently handles more than 500k requests in a minutes, this style of code gave me a peace of mind.

```
class CreateUsersTable
{
	Schema::create('users', function (Blueprint $table) {
		$table->increments('id');
		$table->string('zip_code', 5);
		// ...
	});
}

/**
 * @property Address $address
 */
class User extends Model
{
	public function getAddressAttribute()
	{
		return new Address(
			$this->getAttributeValue('zip_code'),
			// ...
		);
	}

	public function setAddressAttribute(Address $address)
	{
		$this->attributes['zip_code'] = $address->getZipCode();
		// ...
	}
}

class Address
{
	private $zipCode;

	public function __construct(
		string $zipCode = null,
		// ...
	) {
		$this->zipCode = $this->setZipCode($zipCode);
	}

	public function getZipCode()
	{
		return $this->zipCode;
	}

	public function setZipCode(string $zipCode = null)
	{
		if (is_numeric($zipCode) === false || mb_strlen($zipCode) !== 5) {
			throw new InvalidArgumentException();
		}
		$this->zipCode = $zipCode;
	}

	// ...

	public function isEqualTo(Address $other)
	{
		return $this->zipCode === $other->getZipCode()
			// && ...
			;
	}
}

class SomeControllerOrCommandOrService
{
	public function doSomethingWith(User $user)
	{
		$destAddress = $user->address;
		// ...
	}
}
```

FYI, I got a lot of insights from these videos:
- ["PHP UK Conference 2014" by Mathias Verraes - Unbreakable Domain Models](https://www.youtube.com/watch?v=ZJ63ltuwMaE)
- ["Hemoglobin & Hobgoblins" by Ross Tuck](https://www.youtube.com/watch?time_continue=3&v=ajhqScWECMo)

**Comment by Konafets** [comment]
What you do is right ValueObject-wise, but Laravel is not ready for Value Objects. I used them the same way as you but it felt hacky. Every developer needs to know how to use them and since there is no object validation in Laravel you can assign any value to any attribute (existing or not in db) or create an empty object `$user = new User` (which is not correct if you User *must* have an address) and nobody (Laravel) will complain.

There is a blog post about this: https://www.ntaso.com/why-i-dont-use-value-objects-in-laravel-anymore/

**Comment by appkr** [comment]
@Konafets Thanks a million for the feedback and the link. I've read the link as soon as it was posted, and read them again thanks to you. This thread made me think a lot in terms of software design as well as myself. 

While reading the article and navigating supporting links, I encountered inexperienced day's myself, and became red-faced with shame.

Of the discussion I've read on [this article](https://laracasts.com/discuss/channels/eloquent/models-repository-pattern-and-eloquent), the following sentence teached me that I am going too far...

> Eloquent is Active Record, not modelling tool for describing your domain
> 
> - JarekTkaczyk
