### ISSUE TITLE
avoid using request()->all()

### ISSUE THREAD

**Issue by gpedro** [alexeymezenin/laravel-best-practices#22]
request()->all() can be dangerous because when used may cause a security vulnerability.

for example:
```
# database
users:
   - id
  - username
  - password
  - email
  - superuser (bool)

# controller
public function store(Request $request) {
  User::create($request->all());
  return back()->with('alert', 'user created!');
}
```
if am i a hacker-boy and send a payload with `input[name=superuser]=1` magically I will become a superadmin.

---

bad:
```php
public function store(Request $request) {
  User::create($request->all());
  return back()->with('alert', 'user created!');
}
```

good:

```php
public function store(Request $request) {
  User::create($request->only('username', 'password', 'email'));
  return back()->with('alert', 'user created!');
}
```

**Comment by alexeymezenin** [comment]
Thank you for the recommendation. `$request->all()` is safe if you're using validation and the `$fillable` property properly.

In newer versions of the Laravel framework you can use `$request->validate()`, I'll add it to the repository a bit later.

**Comment by gpedro** [comment]
well, idk if i getting a mistake or something. if i'm wrong, please tell me where i getting wrong ... please checkout my demo project. he is a collaborative news submission.
 - https://github.com/gpedro/avoid-request-all-laravel-best-practices

setup: `composer install && php artisan migrate --seed`

paths: 
 - home - `GET /`
 - news form - `GET /news/create`

steps to reproduce:
 - go to home and look the news inserted by the factory.
 - go to news form and submit a news
 - back to home and confirm is the news created on last step is not listed.
 - go to news form and fill all fields and inspect element and add a field named `published` with value `1` and submit
- back to home and confirm is the news created on last step is listed.

**Comment by gpedro** [comment]
a possible solution is set value manually on controller to override. but if i have a default value on database i can just pass null.

```php
#before
News::create($request->all());

#after
$data = $request->all();
$data['published'] = false;
News::create($data);
```

**Comment by jyhsu2000** [comment]
Just remove `published` from `$fillable` is okay.
`$fillable` is for mass assignment.
Setting values of non-fillable properties in this way still works.
```php
$news->published = true;
$news->save();
```
