### ISSUE TITLE
Consider adding full namespaces for non-default Laravel classes

### ISSUE THREAD

**Issue by Tarasovych** [alexeymezenin/laravel-best-practices#26]
An example - [services](https://github.com/alexeymezenin/laravel-best-practices/blob/master/README.md#business-logic-should-be-in-service-class).

Might be curious for people who see this first time, where to put Service classes.

I saw people who told to go `app/Services` and `app/Http/Services`. Some advices might be worth it. My opinion.

P. S. If I'm allowed, I'll contribute my own "opinion".

**Comment by Konafets** [comment]
In my opinion this highly depends on the purpose of the service. If its a API client, I would place it below `HTTP`. Otherwise just below `app/`.

**Comment by alexeymezenin** [comment]
Normally, service classes do not belong to the HTTP layer, so it should be `app/Services`.
