### ISSUE TITLE
Traits and interfaces indistinguishable by name

### ISSUE THREAD

**Issue by thomasmoors** [alexeymezenin/laravel-best-practices#44]
Can't we make it more clear by name if the "class" is a trait or an interfaces as they both are adjectives now. I understand the reasoning but we also need a solution (I think). We might consider recommending creating an interface for every trait.

**Comment by zanozik** [comment]
What are you taking about? Only Traits are adjective. Interface may have "Interface" suffix

**Comment by thomasmoors** [comment]
> What are you taking about? Only Traits are adjective. Interface may have "Interface" suffix

That is litterely an example that this guide puts under "Bad". So I disagree that your statement is true.

**Comment by zanozik** [comment]
@thomasmoors , I was mislead by your description. I totally agree with you.
This "best practices" guide is bad on many levels and this is just only one example. How about *The best way is to use specialized PHP to JS package to transfer the data.* statement? 
I guess the guide author knows better than Laravel devs...
Anyway, moving on :)

**Comment by alexeymezenin** [comment]
@thomasmoors when I've added the naming conventions, I've done a lot of research and I've figured out that most Laravel packages and the framework itself didn't use the `SomeInterface` convention at the time. You probably right about this since PSR naming convention says this

> Interfaces MUST be suffixed by Interface: e.g. Psr\Foo\BarInterface

You could open a new poll on this.

**Comment by alexeymezenin** [comment]
@zanozik

>This "best practices" guide is bad on many levels

This repo represents my experience which is based on ~200 Laravel projects I worked on, books I've read, thousands of answers on StackOverflow, and other Laravel communities. So, I know something. But I don't know everything, so if you feel you know better, just create a new discussion about a specific issue and see if people will like what you're saying. Just saying "this repo is bad" and "this statement is wrong" is nothing.

Also, you're saying this guide is bad. It sounds like you've found a better source, can you share it with us?

**Comment by zanozik** [comment]
200 projects and you didn't notice that Laravel framework is using Interface suffix? Sounds legit.

**Comment by alexeymezenin** [comment]
>200 projects and you didn't notice that Laravel framework is using Interface suffix? Sounds legit.

Check the default User model class which is used by most Laravel apps, what do you see there?

Check `vendor/laravel/framework/src/Illuminate/Contracts` directory for dozens of Laravel interfaces.

As I said, I like the idea of using SomeInterface convention just because that's PSR friendly, but I'm not sure if the Laravel community likes that, so we need a poll.

Also, you chose to ignore my question about a better source. You call the source bad, so there must be a better source, right?

**Comment by poncianodiego** [comment]
@zanozik you are being disrespectufl and kind of annoying. You can criticize but being respectful.

**Comment by thomasmoors** [comment]
> @thomasmoors when I've added the naming conventions, I've done a lot of research and I've figured out that most Laravel packages and the framework itself didn't use the `SomeInterface` convention at the time. You probably right about this since PSR naming convention says this
> 
> > Interfaces MUST be suffixed by Interface: e.g. Psr\Foo\BarInterface
> 
> You could open a new poll on this.

How exactly can I open a poll?

**Comment by alexeymezenin** [comment]
@thomasmoors You could open a new issue and ask people to upvote/downvote with reactions (thumb up or thumb down).

**Comment by gkakosouris** [comment]
Another convention that can be observed thoughout the framework is naming interfaces using adjectives and traits using verbs (?). 

For example:
```
Illuminate\Contracts\Auth\Authenticatable
Illuminate\Auth\CreatesUserProviders
```
I think this solves the naming conflict quite gracefully.
