### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by Tenevyk** [alexeymezenin/laravel-best-practices#62]
Hey there, Alexey!

I want to translate these wonderful practices in **Ukrainian language**.
Which **font** and its size I need to use for the image of Laravel? 
That info would be enough for me to start the translation.

Thank you!

**Comment by alexeymezenin** [comment]
Hi Dmytro,

That would be great.

I'm not sure about the logo since @mikayilsrt added the new logos. @mikayilsrt can you please help with the font info?

**Comment by Tenevyk** [comment]
Thank you!

**Comment by Tenevyk** [comment]
Sorry, Alexey, one more question. 
I should add my language in the list on my own, or you'll add it and I need to translate only?

**Comment by alexeymezenin** [comment]
Can you add it, please? I guess it's a good idea to add it before or after the link to the Russian translation.

**Comment by Tenevyk** [comment]
Okay, I'll do it.

**Comment by mikayilsrt** [comment]
Hi,
For the font I use Arial font in Regular (16px),
If you wish I could publish a PSD file in the project repository.

**Comment by alexeymezenin** [comment]
@mikayilsrt that would be great.

**Comment by Tenevyk** [comment]
> Hi,
> For the font I use Arial font in Regular (16px),
> If you wish I could publish a PSD file in the project repository.
Nice! Thanks.

**Comment by mikayilsrt** [comment]
I create new pull requests to add the PSD file.

**Comment by alexeymezenin** [comment]
@Tenevyk you can download Mikayil's source file from here https://github.com/alexeymezenin/laravel-best-practices/blob/master/images/logo-language.psd

**Comment by Tenevyk** [comment]
@alexeymezenin , thank you!

**Comment by Tenevyk** [comment]
@alexeymezenin , I've added a lot of links in other .md files along with README.md and now I've got a lot of warnings and errors, because in a lot of files are wrong markdown links :(
Is it okay? Should I push it anyway?
Thanks.

**Comment by alexeymezenin** [comment]
@Tenevyk try to use Markdown preview. If the links work in the preview window, you can push it.

**Comment by Tenevyk** [comment]
@alexeymezenin , I think I've got these errors because the default Markdown plugin in PHPStorm can't make anchors work in preview, but it will work in file.

**Comment by mikayilsrt** [comment]
@Tenevyk try to use with **VS code** to show the preview.

**Comment by Tenevyk** [comment]
> @Tenevyk try to use with **VS code** to show the preview.
Okay, thanks. Have tried Sublime, but got nothing even after uploading MarkdownPreview.
