### ISSUE TITLE
Poll: Can we change the rule for Interfaces/Contracts to be suffixed with "Interface"?

### ISSUE THREAD

**Issue by thomasmoors** [alexeymezenin/laravel-best-practices#74]
1. This way it's compatible with [PSR naming conventions](https://www.php-fig.org/bylaws/psr-naming-conventions/).
2. You can differentiate Interfaces from Traits by class name, otherwise they might be the same.

This poll was created based on a suggestion by the author: https://github.com/alexeymezenin/laravel-best-practices/issues/44#issuecomment-651786852
Please upvote with a thumbs up and downvote with a thumbs down.

![image](https://user-images.githubusercontent.com/486765/86213944-c4c6f980-bb7a-11ea-878e-8f85db62196f.png)

**Comment by alexeymezenin** [comment]
Most of the Laravel interfaces do not use the `Interface` suffix, as many Laravel packages and apps. I think that we should follow PSR, but I'd like to hear what do you guys think before making changes.

Please vote.

**Comment by Tpojka** [comment]
Keep in mind that [this](https://wiki.php.net/rfc/namespaced_names_as_token) change will lot of currently not allowed namespaces which also doesn't affect this poll here per se. I just wanted to reveal it as some new option expected in future. Nevertheless I am for PSR standard.

**Comment by thomasmoors** [comment]
@alexeymezenin What would be a same end date?

**Comment by alexeymezenin** [comment]
@thomasmoors I guess a couple of weeks is enough

**Comment by thomasmoors** [comment]
> @thomasmoors I guess a couple of weeks is enough

I think those 4 votes (including 1 of mine) will be it 😄

**Comment by alexeymezenin** [comment]
@thomasmoors I'll make the changes during the next few days.

**Comment by alexeymezenin** [comment]
Done. I've updated all the translations.
